import type { FastifyInstance,FastifyReply,FastifyRequest,preHandlerHookHandler } from 'fastify';
import { z } from 'zod'; import type { AppConfig } from '../../config/index.js'; import type { Repositories } from '../../db/repositories.js'; import { pool } from '../../db/pool.js'; import { PersonalWechatBridgeStore } from './store.js'; import { PersonalWechatBridgeService } from './service.js';
const inbound=z.object({messageId:z.string().min(1).max(200),conversationId:z.string().min(1).max(300),conversationName:z.string().max(300).optional(),text:z.string().min(1).max(8000),isGroup:z.boolean().optional(),receivedAt:z.string().optional()});
const ack=z.object({leaseToken:z.string().min(1),status:z.enum(['sent','failed']),error:z.string().max(1000).optional()});
export function registerPersonalWechatBridgeRoutes(app:FastifyInstance,config:AppConfig,repos:Repositories,allowWeb:preHandlerHookHandler){
 const store=new PersonalWechatBridgeStore(pool); const service=new PersonalWechatBridgeService(config,repos,store);
 async function auth(req:FastifyRequest,reply:FastifyReply){const raw=req.headers.authorization;const token=raw?.startsWith('Bearer ')?raw.slice(7).trim():'';const device=await store.authenticate(token);if(!device){reply.code(401);return reply.send({ok:false,error:'invalid_device_token'})}(req as any).bridgeDevice=device;await store.heartbeat(device.id)}
 app.get('/api/web/bridge/devices',{preHandler:allowWeb},async()=>({ok:true,devices:await store.listDevices()}));
 app.post<{Body:unknown}>('/api/web/bridge/devices',{preHandler:allowWeb},async(req,reply)=>{const p=z.object({name:z.string().min(1).max(100)}).safeParse(req.body);if(!p.success){reply.code(400);return{ok:false,error:'invalid_name'}}return{ok:true,...await store.createDevice(p.data.name,{autoReply:true,groups:false})}});
 app.post<{Body:unknown}>('/api/bridge/v1/messages',{preHandler:auth},async(req,reply)=>{const p=inbound.safeParse(req.body);if(!p.success){reply.code(400);return{ok:false,error:'invalid_message'}}return{ok:true,...await service.ingest((req as any).bridgeDevice,p.data)}});
 app.get<{Querystring:{limit?:string}}>('/api/bridge/v1/outbox',{preHandler:auth},async req=>({ok:true,items:await store.claim((req as any).bridgeDevice.id,Math.min(20,Math.max(1,Number(req.query.limit)||10)))}));
 app.post<{Params:{id:string};Body:unknown}>('/api/bridge/v1/outbox/:id/ack',{preHandler:auth},async(req,reply)=>{const p=ack.safeParse(req.body);if(!p.success){reply.code(400);return{ok:false,error:'invalid_ack'}}const row=await store.ack((req as any).bridgeDevice.id,req.params.id,p.data.leaseToken,p.data.status,p.data.error);if(!row){reply.code(409);return{ok:false,error:'lease_mismatch'}}if(row.task_id){if(p.data.status==='sent')await repos.completeTask(row.task_id,`个人微信已回复：${row.text}`);else await repos.updateTaskStatus(row.task_id,'failed',p.data.error??'Windows client send failed')}return{ok:true}});
 app.post<{Body:{error?:string}}>('/api/bridge/v1/heartbeat',{preHandler:auth},async req=>{await store.heartbeat((req as any).bridgeDevice.id,req.body?.error);return{ok:true}})
}
