namespace TeleOpc.WechatBridge;
public sealed class MainForm:Form {
 readonly NotifyIcon tray=new(){Icon=SystemIcons.Application,Text="Tele-OPC 微信桥接",Visible=true};
 readonly BridgeSettings settings=BridgeSettings.Load(); readonly TextBox server=new(){Width=360};readonly TextBox token=new(){Width=360,UseSystemPasswordChar=true};readonly CheckBox auto=new(){Text="自动回复"};readonly CheckBox groups=new(){Text="处理群聊"};readonly NumericUpDown interval=new(){Minimum=1,Maximum=60};readonly Button toggle=new(){Text="启动",Width=100};readonly Button diagnose=new(){Text="导出微信诊断",Width=130};readonly TextBox log=new(){Multiline=true,ReadOnly=true,ScrollBars=ScrollBars.Vertical,Dock=DockStyle.Fill};CancellationTokenSource? cts;WechatAutomation? wechat;
 public MainForm(){Text="Tele-OPC 个人微信桥接";Width=620;Height=480;server.Text=settings.ServerUrl;token.Text=settings.DeviceToken;auto.Checked=settings.AutoReply;groups.Checked=settings.Groups;interval.Value=settings.PollSeconds;var top=new FlowLayoutPanel{Dock=DockStyle.Top,Height=145,Padding=new Padding(10)};top.Controls.AddRange([new Label{Text="服务器",Width=80},server,new Label{Text="设备令牌",Width=80},token,auto,groups,new Label{Text="轮询秒数"},interval,toggle,diagnose]);Controls.Add(log);Controls.Add(top);toggle.Click+=async(_,_)=>await Toggle();diagnose.Click+=(_,_)=>RunDiagnose();FormClosing+=(_,_)=>{cts?.Cancel();tray.Visible=false;};Resize+=(_,_)=>{if(WindowState==FormWindowState.Minimized){Hide();tray.ShowBalloonTip(1000,"Tele-OPC 微信桥接","客户端仍在后台运行",ToolTipIcon.Info);}};tray.DoubleClick+=(_,_)=>{Show();WindowState=FormWindowState.Normal;Activate();};var menu=new ContextMenuStrip();menu.Items.Add("打开",null,(_,_)=>{Show();WindowState=FormWindowState.Normal;});menu.Items.Add("暂停",null,(_,_)=>cts?.Cancel());menu.Items.Add("退出",null,(_,_)=>Close());tray.ContextMenuStrip=menu;}
 async Task Toggle(){if(cts is not null){cts.Cancel();cts=null;toggle.Text="启动";return;}settings.ServerUrl=server.Text.Trim();settings.DeviceToken=token.Text.Trim();settings.AutoReply=auto.Checked;settings.Groups=groups.Checked;settings.PollSeconds=(int)interval.Value;settings.Save();wechat=new WechatAutomation();if(!wechat.Connect()){Write("未找到微信进程，请先登录桌面微信");return;}cts=new();toggle.Text="暂停";Write("桥接已启动");await Task.Run(()=>Loop(cts.Token));}
 async Task Loop(CancellationToken ct){var api=new BridgeApiClient(settings);while(!ct.IsCancellationRequested){try{var msg=wechat!.ReadCurrentConversation();if(msg is not null&&(!msg.isGroup||settings.Groups))await api.UploadAsync(msg,ct);if(settings.AutoReply)foreach(var item in await api.ClaimAsync(ct)){try{var ok=wechat.Send(item);await api.AckAsync(item,ok,ok?null:"未定位联系人或输入框",ct);}catch(Exception e){await api.AckAsync(item,false,e.Message,ct);}}await api.HeartbeatAsync(null,ct);}catch(Exception e){Write(e.Message);}await Task.Delay(TimeSpan.FromSeconds(settings.PollSeconds),ct);}}
 void RunDiagnose(){try{wechat??=new();if(!wechat.Connect()){Write("未找到微信");return;}Write("诊断文件："+wechat.Diagnose());}catch(Exception e){Write(e.Message);}}
 void Write(string s){if(InvokeRequired){BeginInvoke(()=>Write(s));return;}log.AppendText($"[{DateTime.Now:HH:mm:ss}] {s}\r\n");}
}
