using System.Diagnostics; using System.Security.Cryptography; using System.Text; using FlaUI.Core; using FlaUI.Core.Definitions; using FlaUI.UIA3;
namespace TeleOpc.WechatBridge;
public sealed class WechatAutomation:IDisposable {
 UIA3Automation? automation; FlaUI.Core.Application? app; string? lastFingerprint;
 public bool Connect(){var p=Process.GetProcesses().FirstOrDefault(x=>x.ProcessName.Equals("Weixin",StringComparison.OrdinalIgnoreCase)||x.ProcessName.Equals("WeChat",StringComparison.OrdinalIgnoreCase));if(p is null)return false;automation=new UIA3Automation();app=FlaUI.Core.Application.Attach(p);return true;}
 public WechatInbound? ReadCurrentConversation(){var w=app?.GetMainWindow(automation);if(w is null)return null;var selected=w.FindAllDescendants(cf=>cf.ByControlType(ControlType.ListItem)).FirstOrDefault(x=>x.Patterns.SelectionItem.IsSupported&&x.Patterns.SelectionItem.Pattern.IsSelected.Value);var name=selected?.Name?.Trim();var texts=w.FindAllDescendants(cf=>cf.ByControlType(ControlType.Text)).Select(x=>x.Name?.Trim()).Where(x=>!string.IsNullOrWhiteSpace(x)).ToList();var text=texts.LastOrDefault();if(string.IsNullOrWhiteSpace(name)||string.IsNullOrWhiteSpace(text))return null;var fp=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(name+"\n"+text)));if(fp==lastFingerprint)return null;lastFingerprint=fp;return new(fp,name,name,text,false,DateTimeOffset.UtcNow.ToString("O"));}
 public bool Send(OutboxItem item){var w=app?.GetMainWindow(automation);if(w is null)return false;var selected=w.FindAllDescendants(cf=>cf.ByControlType(ControlType.ListItem)).FirstOrDefault(x=>x.Name?.Trim()==item.conversation_name);selected?.Click();Thread.Sleep(300);var edit=w.FindAllDescendants(cf=>cf.ByControlType(ControlType.Edit)).LastOrDefault();if(edit is null)return false;edit.Focus();Clipboard.SetText(item.text);SendKeys.SendWait("^v");SendKeys.SendWait("{ENTER}");return true;}
 public string Diagnose(){var w=app?.GetMainWindow(automation)??throw new InvalidOperationException("微信未连接");var path=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop),$"wechat-uia-{DateTime.Now:yyyyMMdd-HHmmss}.txt");var lines=w.FindAllDescendants().Take(3000).Select(x=>$"{x.ControlType} | {x.AutomationId} | {x.Name}");File.WriteAllLines(path,lines);return path;}
 public void Dispose(){automation?.Dispose();app?.Dispose();}
}
